version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_dropship
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dropship
      MYSQL_USER: hungpv
      MYSQL_PASSWORD: 123456789
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dropship_network

volumes:
  mysql_data:

networks:
  dropship_network:
    driver: bridge
